<?php

$translations = [
    'homepage.banner.contact' => 'Zapytaj o termin i cenę!',
    'homepage.banner.listen' => 'Posłuchaj nas!',
    'homepage.banner.description' => 'Profesjonalna obsługa imprez',
    'homepage.banner.title' => 'Songo and Zuza',
    'homepage.features.stage.header' => 'Własny sprzęt',
    'homepage.features.stage.text' => 'Dysponujemy profesjonalnym nagłośnieniem i oświetleniem na małe oraz duże sale, jak i imprezy plenerowe.',
    'homepage.features.repertoire.header' => 'Szeroki repertuar',
    'homepage.features.repertoire.text' => 'Wykonujemy utwory polskie i zagraniczne w bardzo szerokim zakresie począwszy od muzyki biesiadnej, poprzez disco, rocka, blues, pop, dance a także standardy muzyki jazzowej.',
    'homepage.features.voices.header' => 'Wykształcenie muzyczne',
    'homepage.features.voices.text' => 'Wszyscy jesteśmy wykształceni muzycznie, bez problemu przygotujemy utwory na daną uroczystość, nawet jeśli jeszcze niema ich w naszym repertuarze.',
    'homepage.features.transport.header' => 'Własny transport',
    'homepage.features.transport.text' => 'Dysponujemy własnym transportem, zawsze dotrzemy na czas. Odległość nie jest dla nas problemem.',
    'homepage.learnMore' => 'Czytaj dalej',
    'link.learnMore.text' => 'Aby dowiedzieć się więcej',
    'link.learnMore.anchor' => 'kliknij tutaj.',
    'news.index.header.title' => 'Aktualności',
    'news.index.header.description' => 'Czyli co tam u nas słychać.',
    'equipment.index.header.title' => 'Sprzęt',
    'equipment.index.header.description' => 'Na czym gramy, że tak fajnie słychać?',
    'homepage.major.title' => "Jeśli szukasz dobrej zabawy i muzyki<br/>na najwyższym poziomie to dobrze trafiłeś :)",
    'homepage.major.description' => 'Jesteśmy zespołem wokalno-instrumentalnym złożonym <br/>z profesjonalnych muzyków grających 100% muzyki na żywo.',
    'menu.home' => 'Home',
    'menu.about' => 'O nas',
    'menu.equipment' => 'Sprzęt',
    'menu.offer' => 'Oferta',
    'menu.history' => 'Historia',
    'menu.gallery' => 'Galeria',
    'menu.repertoire' => 'Repertuar',
    'menu.movies' => 'Filmy',
    'menu.contact' => 'Kontakt',
    'menu.links' => 'Linki',
    'copyrights' => '&copy; songoandzuza.pl'
];